# Data Science With Python Capstone

In [1]:
import requests
from bs4 import BeautifulSoup
import re
import numpy as np
import pandas as pd

In [2]:
%%time
# The code should complete in a minute. 

# Save each recipe information as a list in the list recipes. 
data = []
URL = "https://en.wikipedia.org/wiki/List_of_multiple_Olympic_medalists#In_the_Summer_and_Winter_Games"
page = requests.get(URL)
soup = BeautifulSoup(page.content, "html.parser")

tables = soup.find_all('table')

dfs = []
for table in tables:
    dfs.append(pd.read_html(str(table))[0])

CPU times: total: 703 ms
Wall time: 903 ms

In [3]:
data = dfs[0].copy()

In [4]:
data = data.dropna(axis = 0)
data

,No.,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total
0,1,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23.0,3.0,2.0,28.0
1,2,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9.0,5.0,4.0,18.0
2,3,Marit Bjørgen,Norway,Cross-country skiing,2002–2018,Winter,F,8.0,4.0,3.0,15.0
3,4,Nikolai Andrianov,Soviet Union,Gymnastics,1972–1980,Summer,M,7.0,5.0,3.0,15.0
4,5,Ole Einar Bjørndalen,Norway,Biathlon,1998–2014,Winter,M,8.0,4.0,1.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...
291,290,Piero D'Inzeo,Italy,Equestrian,1956-1972,Summer,M,0.0,2.0,4.0,6.0
292,290,Roald Larsen,Norway,Speed skating,1924-1928,Winter,M,0.0,2.0,4.0,6.0
293,290,Rintje Ritsma,Netherlands,Speed skating,1994-2006,Winter,M,0.0,2.0,4.0,6.0
294,290,Dimitrij Ovtcharov,Germany,Table tennis,2008-2020,Summer,M,0.0,2.0,4.0,6.0
295,294,Harri Kirvesniemi,Finland,Cross-country skiing,1980-1998,Winter,M,0.0,0.0,6.0,6.0

In [5]:
data.to_csv('project_data.csv', index=False)

In [6]:
data = pd.read_csv('project_data.csv')

In [7]:
data['Years'].unique()

array(['2004–2016', '1956–1964', '2002–2018', '1972–1980', '1998–2014',
       '1936–1960', '2006–2022', '1952–1964', '1920–1928', '1980–2004',
       '1992–1998', '1968–1976', '1992–2004', '1992–2020', '1984–2008',
       '1996–2000', '2004–2012', '1968–1972', '1984–1992', '1960–1968',
       '1952–1956', '2004–2020', '1912–1924', '2016–2020', '1984–1996',
       '2012–2020', '1932–1960', '1992–1996', '1996–2004', '1976–1992',
       '2008–2020', '1976–1980', '1992–2002', '1900–1920', '1992–1994',
       '1996–2012', '2000–2004', '1992–2006', '1992–2000', '2006–2018',
       '2010–2018', '1992–2012', '2000–2012', '1928–1936', '2018–2022',
       '1908–1924', '1928–1952', '1980–2000', '1900–1908', '2008–2016',
       '1948–1960', '1964–1988', '2006–2014', '1924–1928', '1984–2004',
       '2000–2016', '1972–1976', '1920–1924', '1924–1936', '1994–2006',
       '1992–2008', '1920–1936', '1980–1988', '1928-1936', '1956–1960',
       '2002–2010', '2014–2022', '2010–2022', '2000–2008', '1920',
       '1956–1976', '1988–1996', '1968–1984', '1904–1908', '1952–1960',
       '1964–1976', '1948–1956', '1984–1994', '1952', '2004–2008',
       '1960–1976', '1968–1980', '2012–2016', '1976–1988', '1980-1992',
       '1988-1994', '2012-2020', '1952-1960', '1948-1952', '2016-2020',
       '2008-2020', '1912-1920', '1988', '1960–1964', '2014-2022', '1904',
       '1920-1924', '1964–1968', '1994-2002', '1984-2000', '1924-1928',
       '1988–1994', '2000-2008', '2008-2012', '2012-2016', '1948-1956',
       '1920-1928', '1952-1964', '1972-1976', '2002-2006', '2002-2018',
       '2004-2016', '2002-2012', '1988-2000', '2000-2004', '1968-1980',
       '1992-2008', '1956-1960', '2000-2012', '1984-1988', '2006-2022',
       '2006-2010', '2010-2018', '2010-2022', '1964-1976', '1976-1980',
       '1992-2000', '1992-2020', '1984', '1896', '1904-1912', '1998-2010',
       '2004-2012', '1998-2006', '1936', '1936-1952', '1924-1936',
       '1908-1920', '1996-2016', '1984-1996', '1924-1932', '2018-2022',
       '1992-1996', '1964-1984', '1956-1964', '1960-1964', '1984-2004',
       '1996-2004', '1988-2006', '1984-1994', '2002-2014', '1960-1972',
       '1980-1988', '1896-1900', '1956-1968', '1984-2012', '1988-1992',
       '1994-2014', '2006-2014', '1956-1972', '1988-2004', '1996-2010',
       '1994-1998', '2002-2010', '1908-1924', '1994-2006', '1980-1998'],
      dtype=object)

In [8]:
data

,No.,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total
0,1,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23.0,3.0,2.0,28.0
1,2,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9.0,5.0,4.0,18.0
2,3,Marit Bjørgen,Norway,Cross-country skiing,2002–2018,Winter,F,8.0,4.0,3.0,15.0
3,4,Nikolai Andrianov,Soviet Union,Gymnastics,1972–1980,Summer,M,7.0,5.0,3.0,15.0
4,5,Ole Einar Bjørndalen,Norway,Biathlon,1998–2014,Winter,M,8.0,4.0,1.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...
291,290,Piero D'Inzeo,Italy,Equestrian,1956-1972,Summer,M,0.0,2.0,4.0,6.0
292,290,Roald Larsen,Norway,Speed skating,1924-1928,Winter,M,0.0,2.0,4.0,6.0
293,290,Rintje Ritsma,Netherlands,Speed skating,1994-2006,Winter,M,0.0,2.0,4.0,6.0
294,290,Dimitrij Ovtcharov,Germany,Table tennis,2008-2020,Summer,M,0.0,2.0,4.0,6.0
295,294,Harri Kirvesniemi,Finland,Cross-country skiing,1980-1998,Winter,M,0.0,0.0,6.0,6.0

In [9]:
data.drop(labels='No.', axis=1, inplace=True)
data

,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total
0,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23.0,3.0,2.0,28.0
1,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9.0,5.0,4.0,18.0
2,Marit Bjørgen,Norway,Cross-country skiing,2002–2018,Winter,F,8.0,4.0,3.0,15.0
3,Nikolai Andrianov,Soviet Union,Gymnastics,1972–1980,Summer,M,7.0,5.0,3.0,15.0
4,Ole Einar Bjørndalen,Norway,Biathlon,1998–2014,Winter,M,8.0,4.0,1.0,13.0
...,...,...,...,...,...,...,...,...,...,...
291,Piero D'Inzeo,Italy,Equestrian,1956-1972,Summer,M,0.0,2.0,4.0,6.0
292,Roald Larsen,Norway,Speed skating,1924-1928,Winter,M,0.0,2.0,4.0,6.0
293,Rintje Ritsma,Netherlands,Speed skating,1994-2006,Winter,M,0.0,2.0,4.0,6.0
294,Dimitrij Ovtcharov,Germany,Table tennis,2008-2020,Summer,M,0.0,2.0,4.0,6.0
295,Harri Kirvesniemi,Finland,Cross-country skiing,1980-1998,Winter,M,0.0,0.0,6.0,6.0

In [10]:
# Extract the first year from the 'Years' column
data['First Medal Year'] = data['Years'].str.extract('^(\d{4})')

# Extract the last year from the 'Years' column
data['Last Medal Year'] = data['Years'].str.extract('(\d{4})[^\d]*$')

In [11]:
data['Last Medal Year'].unique()

array(['2016', '1964', '2018', '1980', '2014', '1960', '2022', '1928',
       '2004', '1998', '1976', '2020', '2008', '2000', '2012', '1972',
       '1992', '1968', '1956', '1924', '1996', '2002', '1920', '1994',
       '2006', '1936', '1952', '1908', '1988', '2010', '1984', '1904',
       '1896', '1912', '1932', '1900'], dtype=object)

In [12]:
data['Last Medal Year'].isnull().sum()

0

In [13]:
data['First Medal Year'] = data['First Medal Year'].astype(int)
data['Last Medal Year'] = data['Last Medal Year'].astype(int)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Athlete           296 non-null    object
 1   Nation            296 non-null    object
 2   Sport             296 non-null    object
 3   Years             296 non-null    object
 4   Games             296 non-null    object
 5   Gender            296 non-null    object
 6   Gold              296 non-null    float64
 7   Silver            296 non-null    float64
 8   Bronze            296 non-null    float64
 9   Total             296 non-null    float64
 10  First Medal Year  296 non-null    int32
 11  Last Medal Year   296 non-null    int32
dtypes: float64(4), int32(2), object(6)
memory usage: 25.6+ KB

In [15]:
data.head(5)

,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total,First Medal Year,Last Medal Year
0,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23.0,3.0,2.0,28.0,2004,2016
1,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9.0,5.0,4.0,18.0,1956,1964
2,Marit Bjørgen,Norway,Cross-country skiing,2002–2018,Winter,F,8.0,4.0,3.0,15.0,2002,2018
3,Nikolai Andrianov,Soviet Union,Gymnastics,1972–1980,Summer,M,7.0,5.0,3.0,15.0,1972,1980
4,Ole Einar Bjørndalen,Norway,Biathlon,1998–2014,Winter,M,8.0,4.0,1.0,13.0,1998,2014

In [16]:
data = data.iloc[:,[0,1,2,10,11,4,5,6,7,8,9]].copy()

In [17]:
data

,Athlete,Nation,Sport,First Medal Year,Last Medal Year,Games,Gender,Gold,Silver,Bronze,Total
0,Michael Phelps,United States,Swimming,2004,2016,Summer,M,23.0,3.0,2.0,28.0
1,Larisa Latynina,Soviet Union,Gymnastics,1956,1964,Summer,F,9.0,5.0,4.0,18.0
2,Marit Bjørgen,Norway,Cross-country skiing,2002,2018,Winter,F,8.0,4.0,3.0,15.0
3,Nikolai Andrianov,Soviet Union,Gymnastics,1972,1980,Summer,M,7.0,5.0,3.0,15.0
4,Ole Einar Bjørndalen,Norway,Biathlon,1998,2014,Winter,M,8.0,4.0,1.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...
291,Piero D'Inzeo,Italy,Equestrian,1956,1972,Summer,M,0.0,2.0,4.0,6.0
292,Roald Larsen,Norway,Speed skating,1924,1928,Winter,M,0.0,2.0,4.0,6.0
293,Rintje Ritsma,Netherlands,Speed skating,1994,2006,Winter,M,0.0,2.0,4.0,6.0
294,Dimitrij Ovtcharov,Germany,Table tennis,2008,2020,Summer,M,0.0,2.0,4.0,6.0
295,Harri Kirvesniemi,Finland,Cross-country skiing,1980,1998,Winter,M,0.0,0.0,6.0,6.0

In [18]:
data['Nation'].unique()

array(['United States', 'Soviet Union', 'Norway', 'Italy', 'Netherlands',
       'Japan', 'Finland', 'East Germany \xa0Germany', 'Germany',
       'Russia', 'Czechoslovakia', 'Australia', 'Hungary',
       'Unified Team \xa0Belarus', 'Soviet Union \xa0Unified Team',
       'Great Britain', 'Belgium', 'Unified Team \xa0Russia', 'Romania',
       'Sweden', 'Olympic Athletes from Russia \xa0ROC', 'Jamaica',
       'United Team of Germany \xa0West Germany',
       'South Korea \xa0Russia', 'East Germany', 'Switzerland', 'France',
       'Russia \xa0ROC', 'China', 'Poland', 'Czech Republic', 'Austria',
       'Zimbabwe', 'Soviet Union \xa0Kazakhstan', 'Canada', 'New Zealand',
       'Croatia', 'South Korea', 'Belarus', 'Slovakia', 'West Germany',
       'Germany \xa0Germany', 'Yugoslavia', 'Ethiopia',
       'Romania \xa0Romania', 'Soviet Union \xa0Unified Team \xa0Russia',
       'Unified Team \xa0Ukraine', 'Australasia \xa0Australia'],
      dtype=object)

In [19]:
country_corrections = {
    "East Germany \xa0Germany": "East Germany",
    "Unified Team \xa0Belarus": "Unified Soviet Team",
    "Soviet Union \xa0Unified Team": "Soviet Union",
    "Unified Team \xa0Russia": "Unified Soviet Team",
    "Olympic Athletes from Russia \xa0ROC": "Russia/ROC",
    "United Team of Germany \xa0West Germany": "West Germany",
    "Russia \xa0ROC": "Russia/ROC",
    "Soviet Union \xa0Kazakhstan": "Soviet Union",
    "Romania \xa0Romania": "Romania",
    "Germany \xa0Germany": "Germany",
    "Soviet Union \xa0Unified Team \xa0Russia": "Soviet Union",
    "Unified Team \xa0Ukraine": "Unified Soviet Team",
    "Australasia \xa0Australia": "Australia",
}

data['Nation'] = data['Nation'].replace(country_corrections)

In [20]:
data

,Athlete,Nation,Sport,First Medal Year,Last Medal Year,Games,Gender,Gold,Silver,Bronze,Total
0,Michael Phelps,United States,Swimming,2004,2016,Summer,M,23.0,3.0,2.0,28.0
1,Larisa Latynina,Soviet Union,Gymnastics,1956,1964,Summer,F,9.0,5.0,4.0,18.0
2,Marit Bjørgen,Norway,Cross-country skiing,2002,2018,Winter,F,8.0,4.0,3.0,15.0
3,Nikolai Andrianov,Soviet Union,Gymnastics,1972,1980,Summer,M,7.0,5.0,3.0,15.0
4,Ole Einar Bjørndalen,Norway,Biathlon,1998,2014,Winter,M,8.0,4.0,1.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...
291,Piero D'Inzeo,Italy,Equestrian,1956,1972,Summer,M,0.0,2.0,4.0,6.0
292,Roald Larsen,Norway,Speed skating,1924,1928,Winter,M,0.0,2.0,4.0,6.0
293,Rintje Ritsma,Netherlands,Speed skating,1994,2006,Winter,M,0.0,2.0,4.0,6.0
294,Dimitrij Ovtcharov,Germany,Table tennis,2008,2020,Summer,M,0.0,2.0,4.0,6.0
295,Harri Kirvesniemi,Finland,Cross-country skiing,1980,1998,Winter,M,0.0,0.0,6.0,6.0

In [21]:
sport_correction = {
    "Cross-Country skiing Nordic combined": "Nordic combined"
}

data['Sport'] = data['Sport'].replace(sport_correction)

In [22]:
data.to_csv('project_data_final.csv', index=False)

In [23]:
#min_first_medal_year = data['First Medal Year'].min()
#min_first_medal_year

1896